# Generated by Django 6.1.1 on 2026-09-17 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0003_studentprofile_school_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], max_length=20, verbose_name='status')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.lesson', verbose_name='lesson')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='marked by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ('-lesson__date', '-lesson__start_time'),
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='unique_attendance_per_lesson')],
            },
        ),
    ]
