# Generated by Django 6.1.1 on 2026-09-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_managers_user_role_studentprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_classes', to='users.teacherprofile', verbose_name='class teacher')),
            ],
            options={
                'verbose_name': 'school class',
                'verbose_name_plural': 'school classes',
                'ordering': ('name',),
            },
        ),
    ]
