# Generated by Django 6.1.1 on 2026-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, help_text='Never edit directly — only apps.gamification.services.award_xp may change this.', verbose_name='total XP'),
        ),
    ]
