# Generated by Django 6.1.1 on 2026-09-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ATTENDANCE', 'Attendance'), ('TEST_PUBLISHED', 'Test published'), ('TEST_RESULT', 'Test result'), ('ACTIVITY_PUBLISHED', 'Activity published'), ('ACTIVITY_RESULT', 'Activity graded'), ('XP_EARNED', 'XP earned'), ('ACHIEVEMENT_UNLOCKED', 'Achievement unlocked'), ('STREAK', 'Streak'), ('LESSON_REMINDER', 'Lesson reminder')], default='GENERAL', max_length=20, verbose_name='category'),
        ),
    ]
