# Generated by Django 6.1.1 on 2026-09-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0002_alter_user_managers_user_role_studentprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.schoolclass', verbose_name='class'),
        ),
    ]
