# Generated by Django 6.1.1 on 2026-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_total_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when a temporary password was issued (e.g. bulk import).', verbose_name='must change password'),
        ),
    ]
