# Generated by Django 6.1.1 on 2026-09-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_timetableslot'),
        ('schools', '0002_schoolclass_total_xp'),
        ('users', '0004_studentprofile_total_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.TextField(verbose_name='text')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Blank = no time limit.', null=True, verbose_name='time limit (minutes)')),
                ('max_xp', models.PositiveSmallIntegerField(default=100, verbose_name='maximum XP')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='schools.schoolclass', verbose_name='class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='academics.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='users.teacherprofile', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'tests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.test', verbose_name='test'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted')], default='IN_PROGRESS', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('score_percent', models.FloatField(blank=True, null=True, verbose_name='score (%)')),
                ('xp_awarded', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='XP awarded')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='users.studentprofile', verbose_name='student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.test', verbose_name='test')),
            ],
            options={
                'verbose_name': 'test attempt',
                'verbose_name_plural': 'test attempts',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question', verbose_name='question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.option', verbose_name='selected option')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.testattempt', verbose_name='attempt')),
            ],
            options={
                'verbose_name': 'test answer',
                'verbose_name_plural': 'test answers',
            },
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='unique_test_attempt'),
        ),
        migrations.AddConstraint(
            model_name='testanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_answer'),
        ),
    ]
