# Generated by Django 6.1.1 on 2026-09-18 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_timetableslot'),
        ('learning', '0001_initial'),
        ('schools', '0002_schoolclass_total_xp'),
        ('users', '0004_studentprofile_total_xp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('activity_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('CHALLENGE', 'Challenge'), ('TYPING', 'Typing'), ('PRACTICAL', 'Practical'), ('SPORTS', 'Sports')], max_length=20, verbose_name='activity type')),
                ('max_xp', models.PositiveSmallIntegerField(default=100, verbose_name='maximum XP')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20, verbose_name='status')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schools.schoolclass', verbose_name='class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='academics.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='users.teacherprofile', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('attachment', models.FileField(blank=True, upload_to='activity_submissions/%Y/%m/', verbose_name='attachment')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.activity', verbose_name='activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'activity submission',
                'verbose_name_plural': 'activity submissions',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('score_percent', models.FloatField(verbose_name='score (%)')),
                ('xp_awarded', models.PositiveSmallIntegerField(verbose_name='XP awarded')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='graded at')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='graded by')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='learning.activitysubmission', verbose_name='submission')),
            ],
            options={
                'verbose_name': 'activity result',
                'verbose_name_plural': 'activity results',
            },
        ),
        migrations.AddConstraint(
            model_name='activitysubmission',
            constraint=models.UniqueConstraint(fields=('activity', 'student'), name='unique_activity_submission'),
        ),
    ]
