# Generated by Django 6.1.1 on 2026-09-17 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_time', models.TimeField(default=datetime.time(8, 0), verbose_name='school start time')),
                ('end_time', models.TimeField(default=datetime.time(13, 10), verbose_name='school end time')),
            ],
            options={
                'verbose_name': 'school time settings',
                'verbose_name_plural': 'school time settings',
            },
        ),
    ]
