# Generated by Django 6.1.1 on 2026-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltimesettings',
            name='long_break_after_period',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='long break after period'),
        ),
        migrations.AddField(
            model_name='schooltimesettings',
            name='long_break_minutes',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='long break (minutes)'),
        ),
        migrations.AddField(
            model_name='schooltimesettings',
            name='period_duration_minutes',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='period duration (minutes)'),
        ),
        migrations.AddField(
            model_name='schooltimesettings',
            name='short_break_minutes',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='short break (minutes)'),
        ),
    ]
