# Generated by Django 6.1.1 on 2026-09-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0003_studentprofile_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schools.schoolclass', verbose_name='class'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='users.teacherprofile', verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='academics.subject', verbose_name='subject'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('school_class', 'date', 'start_time'), name='unique_class_timeslot'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('teacher', 'date', 'start_time'), name='unique_teacher_timeslot'),
        ),
    ]
