# Generated by Django 6.1.1 on 2026-09-17 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        ('users', '0003_studentprofile_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], verbose_name='day of week')),
                ('period_number', models.PositiveSmallIntegerField(verbose_name='period number')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='room')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='schools.schoolclass', verbose_name='class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='academics.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='users.teacherprofile', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'timetable slot',
                'verbose_name_plural': 'timetable slots',
                'ordering': ('day_of_week', 'period_number'),
                'constraints': [models.UniqueConstraint(fields=('school_class', 'day_of_week', 'period_number'), name='unique_class_slot'), models.UniqueConstraint(fields=('teacher', 'day_of_week', 'period_number'), name='unique_teacher_slot')],
            },
        ),
    ]
