# Generated by Django 6.1.1 on 2026-09-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0004_studentprofile_total_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='icon')),
                ('condition_type', models.CharField(choices=[('FIRST_TEST', 'Complete your first test'), ('PERFECT_SCORE', 'Score 100% on a test'), ('XP_THRESHOLD', 'Reach a total XP threshold'), ('STREAK_LENGTH', 'Reach a streak length')], max_length=20, verbose_name='condition type')),
                ('condition_value', models.PositiveIntegerField(default=0, help_text='Meaning depends on condition_type, e.g. an XP or streak-day threshold.', verbose_name='condition value')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'ordering': ('condition_type', 'condition_value'),
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='current streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='longest streak')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='last activity date')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'streak',
                'verbose_name_plural': 'streaks',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('source', models.CharField(choices=[('TEST', 'Test'), ('ACTIVITY', 'Activity')], max_length=20, verbose_name='source')),
                ('reason', models.CharField(max_length=255, verbose_name='reason')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'XP transaction',
                'verbose_name_plural': 'XP transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='unlocked at')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='gamification.achievement', verbose_name='achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_achievements', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student achievement',
                'verbose_name_plural': 'student achievements',
                'ordering': ('-unlocked_at',),
                'constraints': [models.UniqueConstraint(fields=('student', 'achievement'), name='unique_student_achievement')],
            },
        ),
    ]
