# Generated by Django 6.1.1 on 2026-09-18 11:17

from django.db import migrations

STARTER_ACHIEVEMENTS = [
    {
        "name": "First Test",
        "description": "Complete your first test.",
        "icon": "🎯",
        "condition_type": "FIRST_TEST",
        "condition_value": 0,
    },
    {
        "name": "Perfect Score",
        "description": "Score 100% on a test.",
        "icon": "💯",
        "condition_type": "PERFECT_SCORE",
        "condition_value": 0,
    },
    {
        "name": "XP Hunter",
        "description": "Reach 500 total XP.",
        "icon": "⚡",
        "condition_type": "XP_THRESHOLD",
        "condition_value": 500,
    },
    {
        "name": "7 Day Streak",
        "description": "Study 7 days in a row.",
        "icon": "🔥",
        "condition_type": "STREAK_LENGTH",
        "condition_value": 7,
    },
]


def seed_achievements(apps, schema_editor):
    Achievement = apps.get_model("gamification", "Achievement")
    for data in STARTER_ACHIEVEMENTS:
        Achievement.objects.get_or_create(name=data["name"], defaults=data)


def remove_achievements(apps, schema_editor):
    Achievement = apps.get_model("gamification", "Achievement")
    Achievement.objects.filter(name__in=[data["name"] for data in STARTER_ACHIEVEMENTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_achievements, remove_achievements),
    ]
